### ISSUE TITLE
Race condition - Missing a barrier between data-dependent sections

### ISSUE THREAD

**Issue by DimitriosSamakovlis** [nihil21/semg-bss-pulp#1]
Hello,

I realized that there is a race condition in the code. 

Specifically, after line 141 in decomp.c , there should be a barrier since the next loop is data-dependant on the results of the previous function call "mm_unroll_1x8". 

Thank you.

Best,
Dimitrios

**Comment by nihil21** [comment]
Hi,

you're right, I've fixed it. Thank you!

Best,
Mattia
